Rorformation/config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root to: 'pages#home'
  get '/bonjour/(:name)', to: 'pages#salut' ,as:'salut'
  # get '/articles', to: 'posts#index' , as: 'posts'
  resources :posts
end

Rorformation/app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

Rorformation/app/models/post.rb
class Post < ApplicationRecord

end

Rorformation/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

Rorformation/app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def salut
    @name = params[:name]
  end
  def home
  end
end

Rorformation/app/controllers/posts_controller.rb
class PostsController < ApplicationController
  def index
    @posts = Post.all
  end

  def show
    @posts = Post.find(params[:id])
  end

  def edit
    @posts = Post.find(params[:id])
  end

  def update
    @posts = Post.find(params[:id])
    @posts.update(post_param)
    redirect_to posts_path
  end

  def new
  @posts = Post.new
  end

  def create
  post = Post.create(post_param)
  redirect_to posts_path
  end

  def destroy
    @posts = Post.find(params[:id])
    @posts.destroy
    redirect_to posts_path
  end

  private
  def post_param
    params.require(:post).permit(:name, :content)
  end
end

Rorformation/app/helpers/application_helper.rb
module ApplicationHelper
end

Rorformation/app/helpers/posts_helper.rb
module PostsHelper
end

Rorformation/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Rorformation</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-alpha.6/css/bootstrap.min.css" integrity="sha384-rwoIResjU2yc3z8GV/NPeZWAv56rSmLldC3R/AZzGRnGxQQKnKkoFVhFQhNUwEyJ" crossorigin="anonymous">
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-alpha.6/js/bootstrap.min.js" integrity="sha384-vBWWzlZJ8ea9aCX4pEW3rVHjgjt7zpkNpZk+02D9phzyeVkE+jo0ieGizqPLForn" crossorigin="anonymous"></script>
  </head>
  <div>
    <nav class="navbar navbar-fixed-top navbar-dark bg-inverse">
    <a class="navbar-brand" href=<%= root_path %>>RoR Formation</a>
      <a class="nav-link" href=<%= salut_path%> > Salut </a>
      <a class="nav-link" href=<%= posts_path%> > Articles </a>
      <ul class="nav navbar-nav">
      </ul>
    </nav>
    </div>
    <div class="container" style="padding-top: 5rem">
    <%= yield %>
    </div>
</html>

Rorformation/app/views/pages/home.html.erb
Bienvenue sur le site

Rorformation/app/views/pages/salut.html.erb
Salut <%= @name %> comment ça va ? <%= 1 + 1 %>

Rorformation/app/views/posts/edit.html.erb
<h1>Editer l'article</h1>

<%= form_for @posts do |f| %>
<div class="form-group">
  <label>Titre de l'article</label>
  <%= f.text_field :name, class:'form-control'%>
</div>
    <div class="form-group">
      <label>Titre de l'article</label>
      <%= f.text_area :content, class:'form-control'%>
    </div>
    <div class="form-group">
  <button type="submit" class="btn btn-primary">Modifier l'article</button>
    </div>
<% end %>

Rorformation/app/views/posts/index.html.erb
<h1>Articles</h1>
<% @posts.each do |article| %>
    <h3><%= article.name %></h3>
    <!--<p><%= article.content %></p>-->
    <p>
      <a href="<%= post_path(article.id) %>" class="btn btn-primary">Lire la suite</a>
      <a href="<%= edit_post_path(article.id) %>" class="btn btn-primary">Editer l'article</a>
      <a href="<%= post_path(article.id) %>" class="btn btn-danger" data-confirm="Are you sure ? " data-method="DELETE">Supprimer l'article</a>
    </p>
<% end %>

<p>
  <a href="<%= new_post_path %>" class="btn btn-sucess"> Créer un article</a>

</p>

Rorformation/app/views/posts/new.html.erb
<h1>Creer un article</h1>

<%= form_for @posts do |f| %>
    <div class="form-group">
      <label>Titre de l'article</label>
      <%= f.text_field :name, class:'form-control'%>
    </div>
    <div class="form-group">
      <label>Titre de l'article</label>
      <%= f.text_area :content, class:'form-control'%>
    </div>
    <div class="form-group">
      <button type="submit" class="btn btn-primary">Envoyer l'article</button>
    </div>
<% end %>

Rorformation/app/views/posts/show.html.erb
<h1><%= @posts.name %></h1>
<p>
  <%= @posts.content %>
</p>
<a href="<%=posts_path%>" class="btn btn-primary"> Revenir aux articles</a>